apiVersion: v1
kind: Secret
metadata:
  name:  credentials
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: fluent-bit
type: Opaque
data:
  access_key_id: {{ .Values.ycApiKey.keyId | b64enc }}
  access_key: {{ .Values.ycApiKey.accessKey | b64enc }}